### ISSUE TITLE
Unable to pull the docker image

### ISSUE THREAD

**Issue by ssinh10** [BRaVa-genetics/vep105_loftee#2]
I am trying to replicate the  steps in https://github.com/BRaVa-genetics/vep105_loftee/blob/main/README.md.

And I have been able to successfully replicate it till bash download_data.sh and download all the data. However when I try pulling the docker  or singularity, it gives me error. 

Using Docker command :  docker pull ghcr.io/brava-genetics/vep105_loftee:main gives me error as    _Error response from daemon: Head "https://ghcr.io/v2/brava-genetics/vep105_loftee/manifests/main": unauthorized_

Using singularity :  it asks for docker user Id and password, however when I add my docker user Id and password it gives error 

command  : singularity pull --docker-login --disable-cache "vep_data/vep.sif" "docker://ghcr.io/brava-genetics/vep105_loftee:main" 

Error : _FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://ghcr.io/brava-genetics/vep105_loftee:main: Requesting bear token: invalid status code from registry 403 (Forbidden)_

Does this require the github token? Am I missing anything here?

Thanks

**Comment by barneyhill** [comment]
Hi ssinh10,
Good spot! Yeah you'll need to auth with your github username and token - I've added this to the readme.

**Comment by ssinh10** [comment]
Thanks barneyhill,

I created a token and used it to login to the docker, I can login to the docker successfully but when  I try to pull in the docker image it gives the error "Error response from daemon: denied". 

Here is the error log: 

docker login ghcr.io
Username: xxxxx
Password:

Login Succeeded
$ docker pull ghcr.io/brava-genetics/vep105_loftee:main
Error response from daemon: denied


similar error message is given with the singularity option.

Is any user level authentication needed to pull the docker image ? Or some additional steps needed after I login to the docker? 

Thanks for the help.

**Comment by barneyhill** [comment]
Hmm strange - one thing to check is your token scope. Github now requires you explicitly tick all these boxes for each permission when you create a new token.

**Comment by barneyhill** [comment]
Other than that I'll check if I can pull the repo with a different account other than my 'repo owner' account but this seems unlikely to be the issue...

**Comment by ssinh10** [comment]
That's a good input. I recreated a new token with all access.  It gives the same error. I will recheck if I am missing anything from my end as well.

Thanks

**Comment by barneyhill** [comment]
Should be all fixed now! Apologies it turns out that an org's packages are private by default but it's public now.

**Comment by astheeggeggs** [comment]
Yep, was my fault - finger's crossed that's sorted it!

**Comment by ssinh10** [comment]
Awesome thanks, that worked, the issue is resolved. I have a vep.sif file for singularity run now.  

However I am having other issue running the cmd. For plugin dbNSFP,   the download_data.sh downloads file named dbNSFP4.3a.zip, however the cmd mentions it as dbNSFP4.3a_grch38.gz. When I change  the name of the file in cmd from dbNSFP4.3a_grch38.gz to  dbNSFP4.3a.zip, it gives the error as "ERROR: Tabix index file vep_data/dbNSFP4.3a.zip.tbi not found - perhaps you need to create it first?",   and another error I am seeing which is not related to above error  is MSG: ERROR: Cache directory vep_data//homo_sapiens not found. 

I am following the exact directory structure as in the readme file.  Is there any other file named dbNSFP4.3a_grch38.gz, I am not able to find?

Here is the log file 
![image](https://github.com/BRaVa-genetics/vep105_loftee/assets/26766123/b0a9c90b-d5de-42c9-9733-d8a3f3d13014)

**Comment by ssinh10** [comment]
I could resolve the second error by using tar -xvzf homo_sapiens_vep_105_GRCh38.tar.gz, which creates a homo sapiens directory and the the second error is resolved. However I am still trying to figure out the  dbNSFP4.3a.zip error.

**Comment by ssinh10** [comment]
I found this link to process the dbNSFP4 files https://useast.ensembl.org/info/docs/tools/vep/script/vep_example.html .  This has older version of dbNSFP4, but I followed a similar steps for the newer version provided in the download file in this repo. Please let me know if there is any other way to do it or if I am missing anything.

Thanks for your help.

**Comment by barneyhill** [comment]
Ah I had missed dbNSFP4.3a.zip != the previous gzipped version! I've updated the download script to reflect this although won't be able to check if this 100% works till tomorrow.

**Comment by ssinh10** [comment]
Thanks barneyhill , I will wait for your response meanwhile here are the steps I followed to process the newer zip version and coverted it to gz 

unzip dbNSFP4.3a.zip
head -n1 dbNSFP4.3a_variant.chr1 > dbNSFP4.3a.txt
cat dbNSFP4.3a_variant.chr* | grep -v "#" >> dbNSFP4.3a.txt
rm dbNSFP4.3a_variant.chr*
bgzip dbNSFP4.3a.txt
tabix -s 1 -b 2 -e 2 dbNSFP4.3a.txt.gz

And when I run the cmd using this file, it runs fine. But it would be great to work with the file you have added to download script.

Thanks.

**Comment by barneyhill** [comment]
Great, I've added the following into download_bash.sh:

```
unzip vep_data/dbNSFP4.3a.zip -d vep_data/
zcat vep_data/dbNSFP4.3a_variant.chr1.gz | head -n1 > vep_data/dbNSFP4.3a.txt
zcat vep_data/dbNSFP4.3a_variant.chr*.gz | grep -v "#" >> vep_data/dbNSFP4.3a.txt
rm vep_data/dbNSFP4.3a_variant.chr*.gz
bgzip vep_data/dbNSFP4.3a.txt
tabix -s 1 -b 2 -e 2 vep_data/dbNSFP4.3a.txt.gz
```

I've run this from a clean machine and it all works - although does take a couple of hours to convert dbNSFP4.3a.zip  -> dbNSFP4.3a.txt.gz...

**Comment by ssinh10** [comment]
Hi @barneyhill, that's perfect, thanks.
