### ISSUE TITLE
Getting use of uninitialized value 

### ISSUE THREAD

**Issue by ssinh10** [BRaVa-genetics/vep105_loftee#3]
Hi,  I am running the command  successfully, but I am getting this output

![image](https://github.com/BRaVa-genetics/vep105_loftee/assets/26766123/66a3a15c-8396-4d95-8bf0-732ba996e20b)

Should I ignore the " Use of uninitialized value in split at opt/micromamba/share/ensembl-vep-105.0-1/LoF.pm line 562, <$fh> line 8070. and the lines that follow this?

Thanks

**Comment by astheeggeggs** [comment]
Hi @ssinh10,
Thanks for the query! Yes, it's just a warning. I've double checked with the author of loftee and confirmed it's fine to ignore.
All the best,
Duncan

**Comment by ssinh10** [comment]
Great, thanks!
