### ISSUE TITLE
Integrating plugins

### ISSUE THREAD

**Issue by ssinh10** [BRaVa-genetics/vep105_loftee#4]
Hi,

I have been using the docker version of this vep and it has been very useful.

I am trying to integrate a couple of other plugins specifically SpliceAI.pm and AlphaMissense.pm.  Can these two be integrated into this docker? I can see SpliceAI plugin integrated with version 105, but I could not find the AlphaMissense plugin in this version. Is it possible to upgrade the docker to the latest version of vep 110  or is there any specific reason version 105 was selected.

1. Can the docker be upgraded to version 110, so that we can use some of the very useful plugins like AlphaMissense? 
2. Can  SpliceAI.pm and AlphaMissense.pm, be integrated into the docker like dbNSFP4 plugin?

Thank you for any insights and help in advance.

**Comment by barneyhill** [comment]
Hmm so you might have compatibility issues but this could be as simple as dropping [AlphaMissense.pm](https://github.com/Ensembl/VEP_plugins/blob/release/110/AlphaMissense.pm) into the plugin directory: `$MAMBA_ROOT_PREFIX/share/ensembl-vep` during the Dockerfile and then adding it as a flag. (110 may not be required)

As for SpliceAI.pm you should be able to just add a flag to use the plugin with the existing Docker.

**Comment by ssinh10** [comment]
Hi @barneyhill, 

Thank you for your response:
1. For SpliceAI  when I run it as as a plugin it gives warning as _"WARNING: Failed to instantiate plugin SpliceAI: ERROR: No file specified"_.  
Is there a way to add the required files in the download script like dbNSFP4 ?

4. For Alphamissense: I did not understand the meaning of  " _this could be as simple dropping [AlphaMissense.pm](https://github.com/Ensembl/VEP_plugins/blob/release/110/AlphaMissense.pm) into the plugin directory: $MAMBA_ROOT_PREFIX/share/ensembl-vep during the Dockerfile_"  
Does that mean I need to add an install statement in the Dockerfile ?

Thanks again for all the help.
